classdef FitResonanceDisplay < handle
    %FitResonanceDisplay Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        figureHandle (1,1)
        axesArray (1,:)
    end

    properties (Constant, Hidden)
        defaultMinRsqr = 0.85
        defaultStep = 1
        defaultRangeMult = 5
    end

    properties (Access = private, Hidden)
        counter (1,1)
        counterLabel (1,1)
        counterMax (1,1)
        stepField (1,1)
        stepLabel (1,1)
        leftArrow (1,1)
        rightArrow (1,1)
        fitButton (1,1)
        stopButton (1,1)
        instructions (1,1)
        autoFitCheckbox (1,1)
        autoFitFrame (1,1)
        rangeMultField (1,1)
        rangeMultLabel (1,1)
        minRsqrField (1,1)
        minRsqrLabel (1,1)
        quadraticNoiseCheckbox (1,1) 
        rsqrLabel(1,1)
        rsqrDisp (1,1)
        plotRangeField (1,1)
        plotRangeLabel (1,1)
        saveButton (1,1)
        deleteButton (1,1)
    end

    properties
        leftButtonFcn
        rightButtonFcn
        fitButtonFcn
        deleteButtonFcn
        counterCallbackFcn
    end

    properties (Access = {?FMR_library.RawData}, Hidden)
        fmrObject
        cutVariable
        uniqueCutVariableValues
        currentIdx = 0
        nCuts
        fitParams
        uncertFitParams
        xData
        yData
        lastInitialParams = []
    end

    properties (Access = {?FMR_library.RawData}, Hidden, Dependent)
        currentCutVarValue
        nonCutVariable
    end

    properties (Dependent)
        step
        rangeMult
        plotRangeMult
        minrsqr
        autoFit
        isFittingData
        quadraticNoise
    end
    
    methods
        function obj = FitResonanceDisplay()
            %FitResonanceDisplay Construct an instance of this class
            %   Detailed explanation goes here
            import FMR_library.FitResonanceDisplay

            % Create figure handle
            obj.figureHandle = figure('Name', 'Resonance fit plot',...
                                      'NumberTitle','off',...
                                      'Units','normalized',...
                                      'Position', [0.1 0.2 0.8, 0.7],...
                                      'NextPlot', 'add', ...
                                      'WindowState', 'maximized', ...
                                      'KeyPressFcn', @obj.keyPressCallback);

            % Calculate axes positions
            obj.axesArray = gobjects(2, 1);
            padding = 0.05;
            plotWidth = 0.4;
            lowerMargin =  0.215;

            % Create axes handles
            for axeIdx = 1:2
                x0 = 0.1 + (plotWidth + padding) * (axeIdx-1);
                position = [x0 lowerMargin plotWidth 0.7];
                obj.axesArray(axeIdx) = axes('Parent',obj.figureHandle,...
                                             'NextPlot','replacechildren', ...
                                             'Units','normalized', ...
                                             'Position', position, ...
                                             'FontUnits','normalized', ...
                                             'FontSize', 0.025, ...
                                              Box='on', XGrid='on', YGrid='on');
            end

            %--------------------------------------------%
            %                  Plot control              %
            %--------------------------------------------%

            obj.counter = uicontrol('Style', 'edit', ...
                                    'String', '0', ...
                                    'Units', 'normal', ...
                                    'Position', [0.475 0.05 0.05 0.05], ...
                                    'FontUnits', 'normalized', ...
                                    'HorizontalAlignment', 'right', ...
                                    'FontSize', 0.6, ...
                                    'Callback', @obj.counterCallback, ...
                                    'Parent', obj.figureHandle, ...
                                    'Visible', 'on');
            obj.counterLabel = annotation("textbox", ...
                                          "FitBoxToText", "off", ...
                                          "Position", [0.475 0.1 0.1 0.05], ...
                                          "VerticalAlignment", "baseline", ...
                                          "HorizontalAlignment","center",...
                                          "Margin", 0, ...
                                          "FontUnits","normalized", ...
                                          "FontSize", 0.03, ...
                                          "FontWeight","bold", ...
                                          "String", "Plot No.", ...
                                          "EdgeColor", "none", ...
                                          "Visible", "on");
            obj.counterMax = uicontrol('Style', 'text', ...
                                       'String', '/ 0', ...
                                       'FontUnits','normalized', ...
                                       'FontSize', 0.6, ...
                                       'HorizontalAlignment', 'left', ...
                                       'Units', 'normal', ...
                                       'Position',[0.53 0.044 0.053 0.05], ...
                                       'Callback', @obj.minRsqrCallback, ...
                                       'Parent', obj.figureHandle, ...
                                       'Enable', 'inactive', ...
                                       'Visible', 'on');       
            obj.leftArrow = uicontrol('Style','PushButton', ...
                                      'String','◀', ...
                                      'FontUnits', 'normalized', ...
                                      'FontSize', 0.3, ...
                                      'Units', 'normal', ...
                                      'Position',[0.42 0.05 0.05 0.08],...
                                      'Callback', @obj.leftPress,...
                                      'Parent', obj.figureHandle, ...
                                      'Visible', 'on', ...
                                      'KeyPressFcn', @obj.keyPressCallback);
            obj.rightArrow = uicontrol('Style','PushButton', ...
                                       'String','▶', ...
                                       'FontUnits', 'normalized', ...
                                       'FontSize', 0.3, ...
                                       'Units', 'normal', ...
                                       'Position',[0.58 0.05 0.05 0.08],...
                                       'Callback',@obj.rightPress, ...
                                       'Parent', obj.figureHandle, ...
                                       'Visible', 'on','Enable','off', ...
                                       'KeyPressFcn', @obj.keyPressCallback);
            obj.stepLabel = annotation("textbox", ...
                                       "FitBoxToText", "off", ...
                                       "Position", [0.475 0.02 0.05 0.03], ...
                                       "VerticalAlignment", "middle", ...
                                       "HorizontalAlignment", "right",...
                                       "Margin", 0, ...
                                       "FontUnits","normalized", ...
                                       "FontSize", 0.0275, ...
                                       "String", "Step:", ...
                                       "EdgeColor", "none", ...
                                       "Visible", "on");
            obj.stepField = uicontrol('Style', 'edit', ...
                                      'String', string(obj.defaultStep), ...
                                      'FontUnits','normalized', ...
                                      'FontSize', 0.8, ...
                                      'Units', 'normal', ...
                                      'Position', [0.53 0.019 0.03 0.03], ...
                                      'HorizontalAlignment', 'left', ...
                                      'Callback', @obj.stepCallback, ...
                                      'Parent', obj.figureHandle, ...
                                      'Visible', 'on');

            %--------------------------------------------%
            %                 Instructions               %
            %--------------------------------------------%

            obj.instructions = annotation("textbox", ...
                                          "FitBoxToText", "on", ...
                                          "Position", [0.55 0.2 0.4 0.715], ...
                                          "VerticalAlignment", "middle", ...
                                          "HorizontalAlignment","left",...
                                          "FontUnits","normalized", ...
                                          "FontSize", 0.04, ...
                                          "String", "", ...
                                          "BackgroundColor","#add8e6", ...
                                          "Visible", "off");

            %--------------------------------------------%
            %                Fit/Stop buttons            %
            %--------------------------------------------%

            obj.fitButton = uicontrol('Style','PushButton', ...
                                      'String','Start fitting', ...
                                      'FontUnits', 'normalized', ...
                                      'FontSize', 0.4, ...
                                      'Units', 'normal', ...
                                      'Position',[0.1 0.05 0.1 0.08],...
                                      'Callback', @obj.fitButtonPress, ...
                                      'Parent', obj.figureHandle, ...
                                      'Visible', 'on');
            obj.stopButton = uicontrol('Style','PushButton', ...
                                       'String','Stop fitting', ...
                                       'FontUnits', 'normalized', ...
                                       'FontSize', 0.4, ...
                                       'Units', 'normal', ...
                                       'BackgroundColor', '#ff7f7f', ...
                                       'Position',[0.1 0.05 0.1 0.08],...
                                       'Callback', @obj.stopButtonPress, ...
                                       'Parent', obj.figureHandle, ...
                                       'Visible', 'off');

            %--------------------------------------------%
            %                Autofit panel               %
            %--------------------------------------------%

            obj.autoFitFrame = annotation("textbox", ...
                                          "FitBoxToText", "on", ...
                                          "Position", [0.21 0.01 0.15 0.125], ...
                                          "VerticalAlignment", "cap", ...
                                          "HorizontalAlignment","left",...
                                          "FontUnits","normalized", ...
                                          "FontSize", 0.02, ...
                                          "String", "Automatic fitting settings:", ...
                                          "FontWeight", "bold", ...
                                          "BackgroundColor","white", ...
                                          "LineWidth", 1.5, ...
                                          "Visible", "on");
            obj.quadraticNoiseCheckbox = uicontrol('Style', 'checkbox', ...
                                                   'String', 'Quadratic noise', ...
                                                   'Tooltip', 'The fit model will account for quadratic noise around the peak.',  ...
                                                   'FontUnits','normalized', ...
                                                   'FontSize', 0.8, ...
                                                   'Units', 'normal', ...
                                                   'Position', [0.1 0.02 0.1 0.025], ...
                                                   'Parent', obj.figureHandle, ...
                                                   'KeyPressFcn', @obj.keyPressCallback);
            obj.rangeMultLabel = uicontrol('Style', 'text', ...
                                           'String', 'Range multiplier:', ...
                                           'Units', 'normal', ...
                                           'Position', [0.215 0.0425 0.1 0.03], ...
                                           'Tooltip', 'Next fit region is calculated by twice the previous FWHM times the range multiplier.', ...
                                           'HorizontalAlignment', 'left', ...
                                           'BackgroundColor', 'white', ...
                                           'FontUnits', 'normalized', ...
                                           'FontSize', 0.7, ...
                                           'Parent', obj.figureHandle, ...
                                           'Visible', 'on');
            obj.rangeMultField = uicontrol('Style', 'edit', ...
                                           'String', string(obj.defaultRangeMult), ...
                                           'FontUnits','normalized', ...
                                           'FontSize', 0.68, ...
                                           'Units', 'normal', ...
                                           'Position',[0.3 0.0425 0.03 0.03], ...
                                           'Callback', @obj.rangeCallback, ...
                                           'Parent', obj.figureHandle, ...
                                           'Enable', 'off', ...
                                           'Visible', 'on');
            obj.minRsqrLabel = uicontrol('Style', 'text', ...
                                         'String', 'Min. r² threshold:', ...'
                                         'Units', 'normal', ...
                                         'Position', [0.215 0.012 0.1 0.03], ...
                                         'Tooltip', 'Minimum value of r² that auto-fit will consider good enough to continue.', ...
                                         'HorizontalAlignment', 'left', ...
                                         'BackgroundColor', 'white', ...
                                         'FontUnits', 'normalized', ...
                                         'FontSize', 0.7, ...
                                         'Parent', obj.figureHandle, ...
                                         'Visible', 'on');
            obj.minRsqrField = uicontrol('Style', 'edit', ...
                                         'String', string(obj.defaultMinRsqr), ...
                                         'FontUnits','normalized', ...
                                         'FontSize', 0.68, ...
                                         'Units', 'normal', ...
                                         'Position',[0.3 0.012 0.03 0.03], ...
                                         'Callback', @obj.minRsqrCallback, ...
                                         'Parent', obj.figureHandle, ...
                                         'Enable', 'off', ...
                                         'Visible', 'on');
            
            obj.autoFitCheckbox = uicontrol('Style', 'checkbox', ...
                                            'String', 'Automatic fitting', ...
                                            'Tooltip', 'Fitting of the following data will be done automatically.',  ...
                                            'FontUnits','normalized', ...
                                            'FontSize', 0.7, ...
                                            'Units', 'normal', ...
                                            'Position', [0.215 0.074 0.13 0.03], ...
                                            'BackgroundColor', 'white', ...
                                            'Callback', @obj.autoFitCheck, ...
                                            'Parent', obj.figureHandle, ...
                                            'Visible', 'on', ...
                                            'KeyPressFcn', @obj.keyPressCallback);

            %--------------------------------------------%
            %                Fit r² display              %
            %--------------------------------------------%

            obj.rsqrLabel = uicontrol('Style', 'text', ...
                                      'String', 'r² =', ...'
                                      'Units', 'normal', ...
                                      'Position', [0.55 0.95 0.1 0.02], ...
                                      'HorizontalAlignment','left',...
                                      'Tooltip', 'r² value of the fit.', ...
                                      'FontUnits', 'normalized', ...
                                      'FontSize', 1, ...
                                      'Parent', obj.figureHandle, ...
                                      'Visible', 'on');
            obj.rsqrDisp = uicontrol('Style', 'text', ...
                                     'String', '', ...
                                     'FontUnits','normalized', ...
                                     'FontSize', 0.8, ...
                                     'HorizontalAlignment', 'left', ...
                                     'Units', 'normal', ...
                                     'Position',[0.57 0.945 0.03 0.025], ...
                                     'Callback', @obj.minRsqrCallback, ...
                                     'Parent', obj.figureHandle, ...
                                     'Enable', 'inactive', ...
                                     'Visible', 'on');
            obj.plotRangeLabel  = uicontrol('Style', 'text', ...
                                            'String', 'Plot range multiplier:', ...'
                                            'Units', 'normal', ...
                                            'Position', [0.82 0.945 0.1 0.025], ...
                                            'HorizontalAlignment','right',...
                                            'Tooltip', 'Plot X interval width is fit twice the FWHM times the range multiplier.', ...
                                            'FontUnits', 'normalized', ...
                                            'FontSize', 0.8, ...
                                            'Parent', obj.figureHandle, ...
                                            'Visible', 'on');
            obj.plotRangeField = uicontrol('Style', 'edit', ...
                                           'String', string(obj.defaultRangeMult), ...
                                           'FontUnits','normalized', ...
                                           'FontSize', 0.68, ...
                                           'Units', 'normal', ...
                                           'Position',[0.92 0.943 0.03 0.025], ...
                                           'Callback', @obj.plotRangeCallback, ...
                                           'Parent', obj.figureHandle, ...
                                           'Visible', 'on');

            %--------------------------------------------%
            %               Save data button             %
            %--------------------------------------------%

            obj.saveButton = uicontrol('Style','PushButton', ...
                                       'String','Save all', ...
                                       'Tooltip', 'Save fit data to FMR object.', ...
                                       'FontUnits', 'normalized', ...
                                       'FontSize', 0.4, ...
                                       'Units', 'normal', ...
                                       'Position',[0.85 0.02 0.1 0.05],...
                                       'Callback', @obj.saveDataToObject, ...
                                       'Parent', obj.figureHandle, ...
                                       'Visible', 'on', ...
                                       'KeyPressFcn', @obj.keyPressCallback);
            obj.deleteButton = uicontrol('Style','PushButton', ...
                                         'String','Delete current fit', ...
                                         'Tooltip', 'Delete current fit information.', ...
                                         'FontUnits', 'normalized', ...
                                         'BackgroundColor', '#ff7f7f', ...v
                                         'FontSize', 0.4, ...
                                         'Units', 'normal', ...
                                         'Position',[0.85 0.075 0.1 0.05],...
                                         'Callback', @obj.deletePress, ...
                                         'Parent', obj.figureHandle, ...
                                         'Visible', 'on', ...
                                         'KeyPressFcn', @obj.keyPressCallback);
        end
    
        %--------------------------------------------%
        %                  Getters                   %
        %--------------------------------------------%
        
        function step = get.step(obj)
        %GET.STEP Returns the step value
            step = str2double(obj.stepField.String);
        end

        function currVal = get.currentCutVarValue(obj)
        %GET.CURRENTCUTVARVALUE Returns the current value of the
        %                       cut variable.
            currVal = obj.uniqueCutVariableValues(obj.currentIdx);
        end
      
        function nonCutVar = get.nonCutVariable(obj)
        %GET.NONCUTVARIABLE Returns the dependent variable that is
        %                   not the cut variable.
            switch obj.cutVariable
                case "Frequency"
                    nonCutVar = "Field";
                case "Field"
                    nonCutVar = "Frequency";
                otherwise
                    nonCutVar = strings(0);
            end
        end

        function out = get.autoFit(obj)
        %GET.AUTOFIT Returns a logical value: true if automatic fitting
        %            is checked, false if not checked.
            out = logical(obj.autoFitCheckbox.Value);
        end

        function out = get.isFittingData(obj)
        %GET.ISFITTINGDATA Returns a logical value: true if currently
        %                  fitting data, false if not fitting.
            out = logical(strcmp(obj.stopButton.Visible, 'on'));
        end

        function rMult = get.rangeMult(obj)
        %GET.RANGEMULT Returns the range multiplier value
            rMult = str2double(obj.rangeMultField.String);
        end

        function pRMult = get.plotRangeMult(obj)
        %GET.PLOTRANGEMULT Returns the plot range multiplier value
            pRMult = str2double(obj.plotRangeField.String);
        end
        
        function minrs = get.minrsqr(obj)
        %GET.MINRSQR Returns the minimum r^2 value
            minrs = str2double(obj.minRsqrField.String);
        end

        function out = get.quadraticNoise(obj)
        %GET.QUADRATICNOISE Returns a logical value: true if 
        %                   quadratic noise is checked, false otherwise.
            out = logical(obj.quadraticNoiseCheckbox.Value);
        end
        
        %--------------------------------------------%
        %                  Setters                   %
        %--------------------------------------------%

        function setInstructions(obj, instrTxt)
        %SETINSTRUCTIONS Set instructions text and display
        %   If text string is empty, hide instruction panel.
        %   Else, display the input text.
        arguments
            obj (1,1) FMR_library.FitResonanceDisplay
            instrTxt {mustBeTextScalar}
        end
            
            if (strcmp(instrTxt, ""))
                obj.instructions.Visible = "off";
                else
                obj.instructions.Visible = "on";
                obj.instructions.String = instrTxt;
            end
        end
        
        function setCounter(obj)
        %SETCOUNTER Write current index value to counter.
        arguments
                obj (1,1) FMR_library.FitResonanceDisplay
        end
            obj.counter.String = num2str(obj.currentIdx);
        end
   
        function setRsqr(obj, str)
        arguments
            obj FMR_library.FitResonanceDisplay
            str {mustBeTextScalar}
        end
            obj.rsqrDisp.String = str;
        end
    end

    methods (Access = public)
        init(obj, dataObj)

        saveFitParams(obj, fitresult, gof)
    end
end